repos:
  - repo: local
    hooks:
    - id: pyproject-fmt
      name: Run poe pyproject-fmt
      language: system
      entry: poetry run poe pyproject-fmt
      always_run: true
      pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
        exclude: ^(requirements.txt|CHANGELOG.md|runConfigurations/.*|environment/legacy/anchore-poc/application-.*\.tf)$
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: ["--fix=no"]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      -   id: black
  - repo: https://github.com/python-poetry/poetry
    rev: 1.3.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--check"]
      - id: poetry-export
        args: ["--without-hashes", "--with", "dev", "-f", "requirements.txt", "-o", "requirements-dev.txt"]
      - id: poetry-export
        args: ["--without-hashes", "--without", "dev", "-f", "requirements.txt", "-o", "requirements.txt"]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.18.0 # Fill in a tag / sha here
    hooks:
      - id: gitlint
  - repo: git@github.com:SandsB2B/b2b-project-lint.git
    rev: v0.1.7
    hooks:
      - id: b2blint
  - repo: git@github.com:SandsB2B/pre-commit-hook-gitown.git
    rev: v0.2.1
    hooks:
      - id: gitown
        args: [ '--ownership_threshold=10', '--codeowners_filename=CODEOWNERS' ]  # Optional
